### ISSUE TITLE
WSPR hopping mode

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#12]
Would be nice to have automatic band change tracking in FSKView when using WSPR in "hopping" mode.  Or if not hopping, ensure proper frequency reporting as the FSKView is tracking with WSPR/radio using CAT.

**Comment by swharden** [comment]
This is a really interesting idea, thanks for suggesting it! I'll take a closer look at WSTJ-X's hopping mode and see if I can determine how to do this.

In practice though it may not be very helpful, because the frequency displayed on the right of the spectrogram would only show the current (and not historical) frequency.

Maybe an alternative way to implement this is to write the frequency above the list of WSPR spots for each 2 minute segment 🤔

**Comment by K4RCG** [comment]
The alternative sounds like it might be worth a try.

**Comment by swharden** [comment]
rig control is pretty specialized, so I'll probably leave that out (but FSKview is open source so someone else can add it if they want). out-of-band WSPRs are no longer shown (#10) this issue is partially resolved anyway

**Comment by K4RCG** [comment]
Tnx!
