### ISSUE TITLE
unable to save JPG format

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#13]
Unable to change saves grab photo/file type from .png to. jpg.

**Comment by swharden** [comment]
Hey @K4RCG, are you using the latest version? Perhaps double-check that you are, as it gives you the ability to define the file name and file extension.

https://swharden.com/software/FSKview/#latest-stable-version

I'll close this issue for now, but if you confirm you're using the latest version and still have an issue with saving JPG instead of PNG feel free to re-open this issue and I can take a closer look

**Comment by K4RCG** [comment]
Tnx Scott.  I’ll double check.

Bob
