### ISSUE TITLE
FT4/FT8 Trace ID

### ISSUE THREAD

**Issue by K4RCG** [swharden/FSKview#34]
Scott, same behavior noted with v1.0.9.  FSKView will display the callsigns of stations using FT4/8 mode from the "ALL.TXT" of WSJT-X but does not annotate the trace with a corresponding number.  Perhaps this feature is not a good fit for the intended purpose of FSKView QRSS/WSPR viewer?  When trying to use with FT4/FT8 I also have to go into settings and change the path from ALL WSPR to ALL; seems different modes are writing to a different log file.  Additionally, FT4, FT8, and WSPR use different frequencies.  

Otherwise v1.0.9 working great with the QRSS/WSPR combo.

Bob K4RCG

**Comment by swharden** [comment]
> Additionally, FT4, FT8, and WSPR use different frequencies

This sounds like the problem. What are the dial frequencies intended for FT4/FT8?

**Comment by K4RCG** [comment]
Scott, FT8:  3.573, 7.074, 10.136, 14,074, 18,100, 21,074, 24,915, 28,074, 50,31
          FT4:  3.575, 7.047.500, 10,140, 14,080, 18,104, 21,140, 24,919, 28, 180, 50, 318
          JS8: 7.078 (most activity)

There *MAY* be some nuances for thes freqs  due to IARU regions, DX operations, contests, etc.  But this is close.

I'm guessing a "MODE" switch in FSKView would be nice to toggle QRSS, WSPR/QRSS, FT4, FT8, JS8 or other digimodes.  This would allow proper freqs and /or paths to .txt files for thos modes.  Just a thought!!  Not trying to suggest more work for you!!!!!

Bob K4RCG

**Comment by swharden** [comment]
Yeah, I guess I didn't recognize this earlier. Sorry! FSKview is definitely designed to work only with the dial frequencies of WSPR/QRSS. I don't think there's an easy way to modify it to work with different frequencies.

band | WSPR | FT4 | FT8 | JS8
---|---|---|---|---
80m|3.5686|3.575|3.573|
40m|7.0386|7.074|7.0475|7.078
30m|10.1387|10.140|10.136|
20m|14.0956|14.080|14.074|

Just out of curiosity, I can make a special version just for you that supports the frequencies you listed and see what happens, but I probably wouldn't want to support it publicly long term 🙃 at this point I'm curious to see if we can make it happen though because we're so close!

**Comment by swharden** [comment]
I'm creating a version to support everything. It would be helpful if you could double-check this table, and also let me know if frequencies are missing. Does JS8 have more frequencies? Having a link to an authoritative source would be helpful too

![image](https://user-images.githubusercontent.com/4165489/88861242-91a07600-d1cb-11ea-8dab-612ab96605d2.png)

```cs
new WsprBand("WSPR 160m", 1836600),
new WsprBand("WSPR 80m", 3568600),
new WsprBand("WSPR 60m", 5287200),
new WsprBand("WSPR 40m", 7038600),
new WsprBand("WSPR 30m", 10138700),
new WsprBand("WSPR 20m", 14095600),
new WsprBand("WSPR 17m", 18104600),
new WsprBand("WSPR 15m", 21094600),
new WsprBand("WSPR 12m", 24924600),
new WsprBand("WSPR 10m", 28124600),
new WsprBand("WSPR 6m", 50293000),
new WsprBand("WSPR 2m", 144488500),

new WsprBand("FT8 80m", 3_573_000),
new WsprBand("FT8 40m", 7_074_000),
new WsprBand("FT8 30m", 10_136_000),
new WsprBand("FT8 20m", 14_074_000),
new WsprBand("FT8 17m", 18_100_000),
new WsprBand("FT8 15m", 21_074_000),
new WsprBand("FT8 12m", 24_915_000),
new WsprBand("FT8 10m", 28_074_000),
new WsprBand("FT8 6m", 50_310_000),

new WsprBand("FT4 80m", 3_575),
new WsprBand("FT4 40m", 7_047_500),
new WsprBand("FT4 30m", 10_140_000),
new WsprBand("FT4 20m", 14_080_000),
new WsprBand("FT4 17m", 18_104_000),
new WsprBand("FT4 15m", 21_140_000),
new WsprBand("FT4 12m", 24_919_000),
new WsprBand("FT4 10m", 28_180_000),
new WsprBand("FT4 6m", 50_318_000),

new WsprBand("JS8 40m", 7_078_000),
```

**Comment by swharden** [comment]
Okay Bob here's a special version just for you! Want to give it a spin on FT4/FT8/JS8 and see how it goes?

https://swharden.com/software/FSKview/downloads/FSKview-1.0.9b.zip

**Comment by K4RCG** [comment]
Will do Scott!!  It  is WELL beyond my tech ability, but perhaps there is a way to import all WSJT-X freqs (all modes) from that app into FSKView??  Also, JS8 is Jordan Sherer's product.  EXCELLENT work by him, KN4CRD.  Essentially he uses the WSJT de-coder in a QSO format.  I commend his work/research to you.   JS8call.com is his website.  JS8 uses freqs on each band a few KHz away from FT8.

**Comment by K4RCG** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/67662141/88866592-ac3e1380-d1fa-11ea-9add-08a63a9d84db.png)
It's working....but not sure the display really transfers any useful data.  Thoughts??

**Comment by swharden** [comment]
Hey Bob, this is great to see! We seem to be 95% of the way there but it's not quite perfect because it looks like FT4/FT8 transmissions are shorter than 2 minutes and FSKview places the numbers anywhere within a 2 minute horizontal period and adjusts their horizontal offset so they're unlikely to overlap.

For FT4/FT8 transmissions I can probably modify the display to place the marker _exactly_ where the transmission was in time, and this will improve the display. I double-checked and we are lucky, as the timestamps logged have hours minutes and seconds so this should be feasible.

```
191010_125623
YYDDMM_HHMMSS
```

**I'll make a new version later tonight which will improve placement of the numbers, and I'd love your feedback to hear how it works for you! I'll post an updated message here when that new version is ready.**

Regarding supporting all WSJT-X modes, it's possible, but a simpler option is just to add a better spectrogram to WSJT-X and be done with it =]  My goal with FSKview is to create a no-nonsense spectrogram like Argo that you click and it runs with no trouble. Adding all this WSJT-X log reading code adds a lot of complexity I'm not thrilled about... and it really narrows the scope of people who may be interested in this program. Finding the right balance between simplicity and features is difficult to achieve, and I'm figuring this out as I go! Perhaps the best path forward is to identify the modes with the most interest (which I initially thought was WSPR, but now see interest in FT4/8), and tactically supporting just the modes with the most interest, then leaving the onus on the WSJT-X team to make a more feature-rich spectrogram.

NOTE TO SELF: horizontal position of numbers is defined here, so make a special case for FT4/8 spots
https://github.com/swharden/FSKview/blob/2076f02eca50999cc4cfe3dd154af95d40cb2832/src/FSKview/Annotate.cs#L73

**Comment by K4RCG** [comment]
Super!! I’ll test it out when it’s ready, unless T storms are about!!

Aye, WSJT modes are really beyond the scope of your original project. I
only raised these ideas thinking it would be fun to place callsigns on FT8,
FT4, etc traces akin to what you accomplished with WSPR. Perhaps “in your
spare time” LOL you can develop this tool!!

Bob

**Comment by swharden** [comment]
Hey Bob, I only have 1RX going so I can't easily test this on my end. I just released version 1.0.10 which I suspect fixes this problem, but again I can't test it myself...

Want to give it a go and see if it does the trick? https://swharden.com/software/FSKview/#latest-version

**Comment by K4RCG** [comment]
Tnx!! Will do Scott...as soon as the T Storm threat passes.  Probably by
morning....

Bob

**Comment by K4RCG** [comment]
It works! Feedback on github.

Bob
